### ISSUE TITLE
bug: Some colors are very hard to see

### ISSUE THREAD

**Issue by lespea** [pauchiner/pastelnight.nvim#14]
### Did you check docs and existing issues?

- [X] I have read all the pastelnight.nvim docs
- [X] I have searched the existing issues of pastelnight.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Linux 6.7.4

### Describe the bug

Here are two examples where it's very difficult to read text.

https://imgur.com/a/DjyVQoy

The top example is in lualine and the second is in htop (using the kitty/fish theme files).  I also noticed the separator between vim windows is now invisible?  The colors theme to line up with the pictures so I'm pretty sure they're being applied correctly.

### Steps To Reproduce

1. Add theme to neovim
2. Add lualine
3. In setup opts specify `theme = 'pastelnight'`
4. Look at bottom text in lualine some of it is very dark

-- or

1. Add colorscheme to kitty
5. Open htop
6. Look at cpu usage text

### Expected Behavior

Text stands out more so it's easier to read

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .reprpastelnight
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "pauchiner/pastelnight.nvim",
  "pauchiner/pastelnight.nvim",
  -- add any other plugins here
  "nvim-lualine/lualine.nvim",
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("pastelnight")
-- add anything else here
-- You need to set the pastelnight theme in lualine
```

**Comment by pauchiner** [comment]
I just merged a PR increasing the contrasts for the [lualine](https://github.com/nvim-lualine/lualine.nvim/tree/master) and [lightline](https://github.com/itchyny/lightline.vim) plugins. I also updated all the terminal extras to increase the color contrast of the `bright black` the color causing this weird contrast in htop.

Anyway, the relative low contrast of the theme, is a design choice, but I think it would be great to have a colorscheme variant with higher contrast for those who need it. I already opened a issue for this #17.

**Comment by pauchiner** [comment]
The window separator highlight is already set, but is only visible on the vertical windows:

<img width="600" alt="Window Separator Example" src="https://github.com/pauchiner/pastelnight.nvim/assets/49660697/b7b518a2-ae82-4817-ba13-259a2525d79e">

I'm currently researching how to solve this.

**Comment by lespea** [comment]
Looks great, thanks!

Re windows: interesting yeah I do see the window separator now it turns out that for kyazdani42/nvim-tree.lua that separator is invisible which is weird I thought that was just a normal window?  Maybe it's related to why it's invisible on vertical windows but that's just a guess.

**Comment by pauchiner** [comment]
@lespea In fact, the [nvim-tree.lua](https://github.com/nvim-tree/nvim-tree.lua) plugin has it's own highlight for the window border, is independent of the rest of the workspace.

The really issue might be with some conflict between statusline plugins, like [lualine](https://github.com/nvim-lualine/lualine.nvim/tree/master) with the theme base config, which causes the horizontal window border to disappear.

I'm going to close this issue, if you encounter more problems with the theme, feel free to open another.
